version: '3.8'

services:
  chat-server:
    build: .
    container_name: chat-server
    ports:
      - "5555:5555"
    restart: always
    networks:
      - chat-network

  chat-client:
    build: .
    container_name: chat-client
    depends_on:
      - chat-server
    entrypoint: ["python", "chat.py", "client"]
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
